- id: optimize-assets
  name: Optimize Images (SVG, PNG, WebP, JPG)
  description: Optimize all image assets using svgo and caesium-clt
  entry: optimize-assets
  language: script
  files: \.(svg|png|webp|jpe?g)$
  require_serial: false
  pass_filenames: false
  always_run: true 